fix: Add missing offset_encoding
vigoux/architext.nvim pull request #6
Opened 2022-05-03 20:43 UTC by Sh3Rm4n

`apply_text_edits` now requires the offset encoding to be passed.

2022-05-03 21:07 UTC, vigoux requested changes
I was about to work on fixing that!
Just a little comment, and we'll be good to go.

2022-05-03 21:07 UTC, vigoux commented on lua/architext/edit.lua
> +  vim.lsp.util.apply_text_edits(edits, buf, vim.api.nvim_buf_get_option(buf,'fileencoding'))
I think that tree-sitter integration in neovim used UTF8 only for now, so I guess you should set that to UTF8 rather.

2022-05-04 05:37 UTC, vigoux commented
Though I think that tree-sitter should respect this option. I will try to add that to the tree-sitter integration upstream ASAP and we'll see what we can to.

2022-05-04 05:50 UTC, Sh3Rm4n commented
A possible solution might be to pass `'utf-8'` for now to fix the immediate problem (at least with v0.7+) and merge this PR when upstream has support for other encodings. What do you think? 

I'm fine just changing it to 'utf-8', but also fine keeping it for now and waiting for upstream support :)

2022-05-04 11:17 UTC, vigoux commented
Let's fix the problem first, we'll cover edge cases when upstream supports it.

So let's just have `'utf-8'`

2022-05-05 19:37 UTC, vigoux approved these changes

2022-05-05 19:37 UTC, merged